import logo from './logo.svg';
import './App.css';
import React, { useEffect } from 'react'

const S4Payments = require('@shift4/s4payments-web-sdk')


function App() {

  const mode = 'uat'

  useEffect(() => {
    const config = {
      riskId: '', // provided from Shift4
      enabledServices: ['risk', '3ds'],
      appId: '', // Generated by integrator using the S4Payments API
      development: { // only need this for UAT, in production, you can just remove this key completely.
        mode: mode
      }, 
      events: (payload) => {

        if (payload.event === 'THREE_D_SECURE_SUCCESS') {
          
          // If 3DS was needed for a challenge, this is where you would continue from to call back to your server to make the transaction.
          console.log('Do something for 3DS Success')

        } else if (payload.event === 'THREE_D_SECURE_FAILURE') {

          console.log("Do something for 3DS Failure")

        } else if (payload.event === 'THREE_D_SECURE_ERROR') {

          console.log("Do something for 3DS Error")

        } else if (payload.event === 'S4PAYMENTS_INITIALIZED') {
          
          console.log("S4PAYMENTS_INITIALIZED")
          // payload.shift4Session - From the payload
          // payload.riskSessionId - From the payload

          // After you receive this event, you can continue with evaluting the payment on your server.

        } else if (payload.event === 'S4PAYMENTS_CLOSED') {
          // If you are integrating 3DS, and your payment screen just hangs for a while, ~10 minutes,
          // the SDK will shut down 3DS and you will be required to re-initialize the SDK.
        }
      }
    }

    S4Payments.sdk.initialize(config)

  }, [])

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          S4PaymentsWebSDK Risk with 3DS Example
        </a>
      </header>
    </div>
  );
}

export default App;
